// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn84PTtTa4WYQEY2EU_pJvZgl36wFLlSQ',
    appId: '1:370547342389:web:979fe1782e557f0eb6c57c',
    messagingSenderId: '370547342389',
    projectId: 'duapuluhnolnol',
    authDomain: 'duapuluhnolnol.firebaseapp.com',
    storageBucket: 'duapuluhnolnol.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYdWiE_-9kcclKX6xyU7kOq7pr0aXA_a4',
    appId: '1:370547342389:android:e07d230263323964b6c57c',
    messagingSenderId: '370547342389',
    projectId: 'duapuluhnolnol',
    storageBucket: 'duapuluhnolnol.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8KOk3HQRTAGLeLy-aIDRwyQOrMRrcgWk',
    appId: '1:370547342389:ios:0ab97d9833f35bd0b6c57c',
    messagingSenderId: '370547342389',
    projectId: 'duapuluhnolnol',
    storageBucket: 'duapuluhnolnol.appspot.com',
    iosBundleId: 'com.example.duapuluhnolnol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8KOk3HQRTAGLeLy-aIDRwyQOrMRrcgWk',
    appId: '1:370547342389:ios:62b8d10e076455c2b6c57c',
    messagingSenderId: '370547342389',
    projectId: 'duapuluhnolnol',
    storageBucket: 'duapuluhnolnol.appspot.com',
    iosBundleId: 'com.example.duapuluhnolnol.RunnerTests',
  );
}
